name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gitleaks-action with defaults
        uses: partior-libs/gcs-gitleaks-scan@main
      - name: gitleaks-action with config
        uses: partior-libs/gcs-gitleaks-scan@main
        with:
          config-path: .gitleaks.yml
